version: '3.8'

services:
  worker:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: telegram-worker
    restart: unless-stopped
    env_file:
      - .env
    volumes:
      - .:/app
      - ./anon.session:/app/anon.session
